sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install codecov

script:
  - coverage run test.py

after_success:
  - curl -s https://raw.githubusercontent.com/abranhe/hack/master/travis/success | bash -s
